language: php

sudo: required

env:
  - DRUPAL_ROOT=/var/www/html

services:
  - docker

before_script:
  - docker pull bcondon/docker_tripal3

script:
  - ls
  - docker run -d -v ".":/var/www/html/sites/all/modules/tripal_elaticsearch --name tripal -p 8080:80 bcondon/docker_tripal3 /bin/bash
  - docker exec tripal bash -c "mkdir /var/www/html/sites/all/modules/tripal_elaticsearch"
  - sleep 20
  - docker exec tripal bash -c "cd /var/www/html && drush pm-enable -y tripal_elasticsearch"
  - docker exec tripal bash -c 'cd /var/www/html/sites/all/modules/tripal_elaticsearch && composer install && DRUPAL_ROOT="/var/www/html" ./vendor/bin/phpunit'
