language: php

php:
  - 7.1

sudo: required

services:
  - docker

env:
  - DRUPAL_ROOT=/var/www/html

before_script:
  - docker-compose up -d
  - sleep 60
  - cp tests/travis.env tests/.env

script:
  - docker-compose exec app drush en -y tripal_elasticsearch
  - docker-compose exec app bash -c 'cd /modules/tripal_elasticsearch && composer install && ./vendor/bin/phpunit'
