language: php

php:
  - 7.1

sudo: required

services:
  - docker

before_script:
  - docker-compose up -d
  - composer install

script:
  - sleep 30 # Allow docker to start up in the background
  - docker-compose exec app drush pm-enable -y tripal_elasticsearch
  - docker-compose exec app bash -c 'cd /modules/tripal_elaticsearch && ./vendor/bin/phpunit'
