version: '3'

services:
  app:
    image: 'statonlab/tripal3'
    environment:
      - DRUPAL_ROOT=/var/www/html
    volumes:
      - .:/modules/tripal_elasticsearch
      - ./vendor:/var/www/html/sites/all/libraries/elasticsearch-php
  elasticsearch:
    image: 'elasticsearch:6.6.1'
    ports:
      - "9201:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./synonyms:/usr/share/elasticsearch/config/analysis
  kibana:
    image: 'kibana:6.6.1'
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_HOST: "0.0.0.0"

volumes:
  es_data:
